{"links": {"self": {"href": "data/repositories/osrf/vrx/issues/154/comments/53688369.json"}, "html": {"href": "#!/osrf/vrx/issues/154#comment-53688369"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/vrx/issues/154.json"}}, "type": "issue", "id": 154, "repository": {"links": {"self": {"href": "data/repositories/osrf/vrx.json"}, "html": {"href": "#!/osrf/vrx"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e278ca38-7edb-4e62-b785-46dff5617d98}ts=2274605"}}, "type": "repository", "name": "vrx", "full_name": "osrf/vrx", "uuid": "{e278ca38-7edb-4e62-b785-46dff5617d98}"}, "title": "Getting error while launching  roslaunch vrx_gazebo vrx.launch"}, "content": {"raw": "I installed the vrx package by: sudo apt install ros-melodic-vrx-gazebo  and then did source /opt/ros/melodic/setup.bash.  I tried to launch above file its giving me the error said above.", "markup": "markdown", "html": "<p>I installed the vrx package by: sudo apt install ros-melodic-vrx-gazebo  and then did source /opt/ros/melodic/setup.bash.  I tried to launch above file its giving me the error said above.</p>", "type": "rendered"}, "created_on": "2019-08-31T03:40:19.146576+00:00", "user": {"display_name": "SaailN", "uuid": "{73eb19f8-43a7-41f2-940a-48e1668a5d67}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B73eb19f8-43a7-41f2-940a-48e1668a5d67%7D"}, "html": {"href": "https://bitbucket.org/%7B73eb19f8-43a7-41f2-940a-48e1668a5d67%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/4cb030ccb692ba3174e22b039878ba89d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsS-0.png"}}, "nickname": "SaailN", "type": "user", "account_id": "5d69eab2a46a5b0bd7fa3f93"}, "updated_on": null, "type": "issue_comment", "id": 53688369}