{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/vrx.json"}, "html": {"href": "#!/osrf/vrx"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e278ca38-7edb-4e62-b785-46dff5617d98}ts=2274605"}}, "type": "repository", "name": "vrx", "full_name": "osrf/vrx", "uuid": "{e278ca38-7edb-4e62-b785-46dff5617d98}"}, "links": {"attachments": {"href": "data/repositories/osrf/vrx/issues/4/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/vrx/issues/4.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/vrx/issues/4/watch"}, "comments": {"href": "data/repositories/osrf/vrx/issues/4/comments_page=1.json"}, "html": {"href": "#!/osrf/vrx/issues/4/vcs-command-could-not-determine-url"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/vrx/issues/4/vote"}}, "reporter": {"display_name": "Raymond Andrade", "uuid": "{444c12f5-372b-4013-8fa6-03f6f225562c}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B444c12f5-372b-4013-8fa6-03f6f225562c%7D"}, "html": {"href": "https://bitbucket.org/%7B444c12f5-372b-4013-8fa6-03f6f225562c%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/5aa33c7ef958b02df135a56f/f1b4f951-2ef5-47df-bf65-399cd26fd36e/128"}}, "nickname": "808brick", "type": "user", "account_id": "5aa33c7ef958b02df135a56f"}, "title": "vcs command could not determine url", "component": null, "votes": 0, "watches": 1, "content": {"raw": "When running the command:\r\n\r\n\r\n```\r\n#!unix\r\n\r\nvcs import . < vmrc.repos\r\n```\r\n\r\n\r\nI get the following output:\r\n\r\n\r\n```\r\n#!Unix\r\n\r\n=== ./robotx_gazebo (hg) ===\r\nCould not determine url: not found!\r\n```\r\n\r\nIt's worth noting that I needed to use:\r\n```\r\n#!unix\r\n\r\nsudo pip install vcstools\r\n```\r\nto install vcstools without an error.\r\n\r\nIf I try to proceed with the rest of the tutorial, when I try to launch the project I get:\r\n\r\n\r\n```\r\n#!unix\r\n\r\n[sandisland.launch] is neither a launch file in package [robotx_gazebo] nor is [robotx_gazebo] a launch file name\r\nThe traceback for the exception was written to the log file\r\n```\r\n\r\nI am running Ubuntu 16.04 and had ROS Kinetic installed prior", "markup": "markdown", "html": "<p>When running the command:</p>\n<div class=\"codehilite language-unix\"><pre><span></span><span class=\"n\">vcs</span> <span class=\"kn\">import</span> <span class=\"o\">.</span> <span class=\"o\">&lt;</span> <span class=\"n\">vmrc</span><span class=\"o\">.</span><span class=\"n\">repos</span>\n</pre></div>\n\n\n<p>I get the following output:</p>\n<div class=\"codehilite language-unix\"><pre><span></span>=== ./robotx_gazebo (hg) ===\nCould not determine url: not found!\n</pre></div>\n\n\n<p>It's worth noting that I needed to use:</p>\n<div class=\"codehilite language-unix\"><pre><span></span>sudo pip install vcstools\n</pre></div>\n\n\n<p>to install vcstools without an error.</p>\n<p>If I try to proceed with the rest of the tutorial, when I try to launch the project I get:</p>\n<div class=\"codehilite language-unix\"><pre><span></span>[sandisland.launch] is neither a launch file in package [robotx_gazebo] nor is [robotx_gazebo] a launch file name\nThe traceback for the exception was written to the log file\n</pre></div>\n\n\n<p>I am running Ubuntu 16.04 and had ROS Kinetic installed prior</p>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2018-05-19T11:02:51.176693+00:00", "milestone": null, "updated_on": "2018-05-20T01:10:12.258304+00:00", "type": "issue", "id": 4}