{"links": {"self": {"href": "data/repositories/osrf/vrx/issues/152/comments/54679274.json"}, "html": {"href": "#!/osrf/vrx/issues/152#comment-54679274"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/vrx/issues/152.json"}}, "type": "issue", "id": 152, "repository": {"links": {"self": {"href": "data/repositories/osrf/vrx.json"}, "html": {"href": "#!/osrf/vrx"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e278ca38-7edb-4e62-b785-46dff5617d98}ts=2274605"}}, "type": "repository", "name": "vrx", "full_name": "osrf/vrx", "uuid": "{e278ca38-7edb-4e62-b785-46dff5617d98}"}, "title": "Runtime Error During World Generation"}, "content": {"raw": "I believe this issue is resolved. @{5b96b66385af94340e7cabce} , can you confirm?", "markup": "markdown", "html": "<p>I believe this issue is resolved. <span class=\"ap-mention\" data-atlassian-id=\"5b96b66385af94340e7cabce\">@Tyler Lum</span> , can you confirm?</p>", "type": "rendered"}, "created_on": "2019-11-05T18:12:49.730969+00:00", "user": {"display_name": "Michael McCarrin", "uuid": "{3c3f500d-bbf6-472c-b8f7-627e5eabc226}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3c3f500d-bbf6-472c-b8f7-627e5eabc226%7D"}, "html": {"href": "https://bitbucket.org/%7B3c3f500d-bbf6-472c-b8f7-627e5eabc226%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a50abc93a3175f92c79e7521dfe089c0d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMM-0.png"}}, "nickname": "m1chaelm", "type": "user", "account_id": "5b2a9176467c9a09caa71ab1"}, "updated_on": null, "type": "issue_comment", "id": 54679274}